### ISSUE TITLE
建議可以直接新增利害關係人

### ISSUE THREAD

**Issue by mark19891107** [PDIS/issue-based-mapping-v2#1]
在使用順序上，我的習慣是先打問題
但是打問題的時候會需要關聯利害關係人
這時候打開就會是空的（因為利害關係人其實在主頁面的第六個column)
但是可以讓人輸入ＸＤ
但是輸入的結果不如預期（以為會自動新增好利害關係人）

所以建議可以在輸入後直接在利害關係人的 column 加一張卡

**Comment by XanxusX** [comment]
忘記關 done
