### ISSUE TITLE
【功能】便利貼上的tag要分兩種顏色（to/from）

### ISSUE THREAD

**Issue by fangjui** [PDIS/issue-based-mapping-v2#14]
to的意思是：這張便利貼上的內容要問誰
from的意思是：這張便利貼的內容是來自誰

**Comment by XanxusX** [comment]
如果在問題上有to跟from
回應或解法是不是也要有to跟from
造成每張卡片上都有滿滿的tag
是否考慮其他呈現方式

**Comment by XanxusX** [comment]
關聯利害關係人(資料來源)
關聯利害關係人(要向誰提問)

**Comment by XanxusX** [comment]
done
