### ISSUE TITLE
attachments are not revealed in the front page

### ISSUE THREAD

**Issue by shuyanglin** [PDIS/issue-based-mapping-v2#15]
When attaching files to "資料/文件/連結", it's not possible to know what files have been attached.
Although checking from the "backend" (our Trello board, actually), there are files attached to certain cards, but attachments are not revealed in the front page.

![screenshot 2018-07-16 04 10 19](https://user-images.githubusercontent.com/4061541/42741917-42937426-88ae-11e8-88ec-abf2f2a34586.png)

![screenshot 2018-07-16 04 13 48](https://user-images.githubusercontent.com/4061541/42741963-a9188d80-88ae-11e8-8644-bedc374bcda2.png)

**Comment by XanxusX** [comment]
done
