### ISSUE TITLE
重複編輯每張卡的利害關係人時，之前存在的會被重複新增

### ISSUE THREAD

**Issue by mark19891107** [PDIS/issue-based-mapping-v2#2]
類似下面這張圖顯示

我已經選過「附議人」並且儲存，再編輯一次的時候「附議人」應該要是打勾的

<img width="601" alt="2018-05-28 11 47 07" src="https://user-images.githubusercontent.com/7321879/40596380-f23e91a2-626c-11e8-961b-8b0cba396fd9.png">

**Comment by XanxusX** [comment]
fixed
